import type { Metadata } from "next";
import { League_Spartan, Silkscreen } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
});

const silkScreen = Silkscreen({
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${leagueSpartan.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
